import type { Task, List, Tag } from '@/lib/types';
import { addDays, subDays } from 'date-fns';

const today = new Date();

export const initialLists: List[] = [
  { id: 'my-day', title: 'My Day', icon: 'Sun', color: 'gray' },
  { id: 'important', title: 'Important', icon: 'Star', color: 'red' },
  { id: 'tasks', title: 'Tasks', icon: 'Home', color: 'gray' },
  { id: 'work', title: 'Work', icon: 'Briefcase', color: 'blue' },
  { id: 'personal', title: 'Personal', icon: 'User', color: 'green' },
  { id: 'groceries', title: 'Grocery Shopping', icon: 'ShoppingCart', color: 'orange' },
];

export const initialTags: Tag[] = [
  { id: 'urgent', label: 'Urgent' },
  { id: 'home', label: 'Home' },
  { id: 'work', label: 'Work' },
  { id: 'project-aqua', label: 'Project Aqua' },
  { id: 'quick-task', label: 'Quick Task' },
];

export const initialTasks: Task[] = [
  {
    id: 'TASK-001',
    title: 'Design landing page hero section',
    description: 'Create a visually stunning hero section with a clear call-to-action.',
    completed: false,
    isMyDay: false,
    isImportant: true,
    dueDate: addDays(today, 2).toISOString(),
    duration: 120,
    listId: 'work',
    tagIds: ['project-aqua', 'urgent'],
    subtasks: [],
    createdAt: subDays(today, 5).toISOString(),
  },
  {
    id: 'TASK-002',
    title: 'Develop navigation component',
    description: 'Build a responsive and accessible navigation bar for the website.',
    completed: false,
    isMyDay: false,
    isImportant: false,
    dueDate: addDays(today, 3).toISOString(),
    duration: 90,
    listId: 'work',
    tagIds: ['project-aqua'],
    subtasks: [],
    createdAt: subDays(today, 4).toISOString(),
  },
  {
    id: 'TASK-003',
    title: 'Buy milk, eggs, and bread',
    description: '',
    completed: false,
    isMyDay: false,
    isImportant: false,
    listId: 'groceries',
    tagIds: [],
    subtasks: [],
    createdAt: subDays(today, 1).toISOString(),
  },
  {
    id: 'TASK-004',
    title: 'Schedule dentist appointment',
    description: 'Annual check-up and cleaning.',
    completed: true,
    isMyDay: false,
    isImportant: false,
    listId: 'personal',
    tagIds: ['home'],
    subtasks: [],
    createdAt: subDays(today, 10).toISOString(),
    dueDate: subDays(today, 2).toISOString(),
  },
  {
    id: 'TASK-005',
    title: 'Finalize Q3 report',
    description: 'Compile sales data and performance metrics for the quarterly report.',
    completed: false,
    isMyDay: true,
    isImportant: true,
    dueDate: today.toISOString(),
    duration: 180,
    listId: 'work',
    tagIds: ['urgent', 'work'],
    subtasks: [],
    createdAt: subDays(today, 3).toISOString(),
  },
  {
    id: 'TASK-006',
    title: 'Call mom',
    description: 'Catch up with mom.',
    completed: false,
    isMyDay: false,
    isImportant: false,
    listId: 'personal',
    tagIds: ['home'],
    subtasks: [],
    createdAt: subDays(today, 2).toISOString(),
  },
  {
    id: 'TASK-007',
    title: 'Water the plants',
    description: 'The fiddle leaf fig looks a bit sad.',
    completed: false,
    isMyDay: true,
    isImportant: false,
    startTime: new Date(new Date().setHours(9, 0, 0, 0)).toISOString(),
    duration: 15,
    listId: 'tasks',
    tagIds: ['home', 'quick-task'],
    subtasks: [
      { id: 'SUB-001', title: 'Check soil moisture', completed: true },
      { id: 'SUB-002', title: 'Add fertilizer', completed: false },
    ],
    createdAt: subDays(today, 1).toISOString(),
  },
    {
    id: 'TASK-008',
    title: 'Pay electricity bill',
    description: 'Bill is due at the end of the week.',
    completed: false,
    isMyDay: false,
    isImportant: true,
    dueDate: addDays(today, 4).toISOString(),
    duration: 10,
    listId: 'personal',
    tagIds: ['home', 'urgent'],
    subtasks: [],
    createdAt: subDays(today, 2).toISOString(),
  },
];
